name: SmarterWes
favicon: null
layout_spectrum: 0.4029113235883415
typography_spectrum: 0.2649101179558784
title: The Never Ending Pursuit of a Smarter Version of Me™
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d120e'
    - '#f7feee'
    - '#748178'
    - '#9bb9ad'
    - '#f4554f'
  brandStrength: 0.2444285557139665
  lightness: 0.06521838018670678
  saturation: 0.6219294560141861
  rhythmicContrast: 0.12374450289644301
purpose: []
