name: SmarterWes
favicon: null
layout_spectrum: 0.4029113235883415
typography_spectrum: 0.2649101179558784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2444285557139665
  lightness: 0.06521838018670678
  saturation: 0.6219294560141861
  rhythmicContrast: 0.12374450289644301
purpose: []
